In [1]:
import igraph
import pandas as pd
import numpy as np
from numpy import linalg as LA

## Data Preprocessing

In [2]:
graph_data = pd.read_csv("manufacturing_emails_temporal_network.csv", sep = ",")

In [3]:
graph_data.head(5)

node1  node2  timestamp
0      1      2          1
1      1      3          1
2      1      4          1
3      1      5          1
4      1      6          1

In [4]:
graph_data_nodes = graph_data.drop(["timestamp"], axis=1)

In [5]:
graph_data_nodes.head(5)

node1  node2
0      1      2
1      1      3
2      1      4
3      1      5
4      1      6

In [27]:
G_predata = [tuple(x) for x in graph_data_nodes.values]

### Generate Small Graph Edge List for testing

In [73]:
testG = G_predata[1:5]
repeat_list = [(3,1),(1,3),(3,5)]
testG.extend(repeat_list)
testG

[(1, 3), (1, 4), (1, 5), (1, 6), (3, 1), (1, 3), (3, 5)]

In [74]:
tuple(set(tuple(sorted(i)) for i in testG)) #Delete repeated tuples

((1, 3), (1, 4), (1, 5), (1, 6), (3, 5))

In [75]:
testG  = list(set(tuple(sorted(i)) for i in testG))

### Aggregated Graph Edge List 

In [109]:
G_A_edgelist = list(set(tuple(sorted(i)) for i in G_predata))
# if you need tupleG_A_edgelist = tuple(set(tuple(sorted(i)) for i in G_predata))

In [34]:
#G_A = igraph.Graph.TupleList(G_A, directed = False)

## Question A

## Question A.7

### Small Graph Test

In [99]:
n = max(testG,key=lambda item:item[1])[1]

In [85]:
#import numpy as np

In [98]:
testG_a_matrix = np.zeros((n,n))

In [104]:
for node1,node2 in testG:
    testG_a_matrix[node1-1][node2-1] = 1
    testG_a_matrix[node2-1][node1-1] = 1
print(testG_a_matrix)

[[0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]


In [105]:
#from numpy import linalg as LA

In [108]:
w,v = LA.eig(testG_a_matrix)
testG_maxeigen = max(w)
print(w)
print(testG_maxeigen)

[-1.8136065   2.34292308  0.47068342  0.         -1.          0.        ]
2.3429230827771694


## Aggregated graph

In [110]:
Node = max(G_A_edgelist,key=lambda item:item[1])[1]

In [111]:
Node

167

In [112]:
G_A_a_matrix = np.zeros((Node,Node))

In [113]:
for node1,node2 in G_A_edgelist:
    G_A_a_matrix[node1-1][node2-1] = 1
    G_A_a_matrix[node2-1][node1-1] = 1

In [114]:
w,v = LA.eig(G_A_a_matrix)
G_A_maxeigen = max(w)
print(G_A_maxeigen)

(60.63926551053454+0j)


In [115]:
import csv 

## Question A.8

In [134]:
G_A_l_matrix = np.zeros((Node,Node))

In [135]:
for row in range(0,Node):
    G_A_l_matrix[row][row]= sum(G_A_a_matrix[row])   

In [136]:
G_A_l_matrix = G_A_l_matrix-G_A_a_matrix

array([130.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,
        -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,
        -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,
        -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,
        -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,
        -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,
        -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,
        -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,
        -1.,  -1.,  -1.,   0.,  -1.,  -1.,  -1.,  -1.,   0.,  -1.,  -1.,
        -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,
        -1.,  -1.,  -1.,   0.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,
        -1.,  -1.,  -1.,  -1.,  -1.,   0.,  -1.,  -1.,  -1.,   0.,   0.,
        -1.,  -1.,   0.,  -1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,  -1.,   0.,  -

In [157]:
w,v = LA.eig(G_A_l_matrix)
G_A_l_maxeigen = max(w)
G_A_l_maxeigen

(140.00159026290203+0j)

In [161]:
G_A_l_eigin = list(w)
G_A_l_eigin.remove(G_A_l_maxeigen)
G_A_l_2nd_maxeigin = max(G_A_l_eigin)
G_A_l_2nd_maxeigin

(137.0092622410165+0j)